<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__category_banner_image</name>
   <tag></tag>
   <elementGuidId>12274d12-9c8c-46c3-9cdb-ca8ca9ff9376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.category_banner_image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>658ca4c0-b695-4e6f-a0e3-a6e1e96efae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg</value>
      <webElementGuid>87c97f5d-e1a0-49a1-b1f0-4c6e31ecec04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>category_banner_image</value>
      <webElementGuid>6c5d24ce-4ebe-46e2-8978-af008c4feebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;col-full&quot;]/div[@class=&quot;wbm_banner_image banner&quot;]/img[@class=&quot;category_banner_image&quot;]</value>
      <webElementGuid>62519ae0-9710-4e28-8f17-fcf2c7291de1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/img</value>
      <webElementGuid>12482fb0-ca7f-476d-9396-e8299d15c939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg')]</value>
      <webElementGuid>e56c83ad-563f-4b9e-a608-227ef79bb24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>fd741f92-dc5c-4a2e-96a5-02d1de7e172c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://craferia.com/wp-content/uploads/2023/10/musical_showpiece.jpg']</value>
      <webElementGuid>50718a40-c86e-4b95-a178-480fec01ac91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
