<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Instagram</name>
   <tag></tag>
   <elementGuidId>f3c71074-5912-4205-8af1-dc92865888c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.wp-social-link.wp-social-link-instagram.wp-block-social-link > a.wp-block-social-link-anchor > span.wp-block-social-link-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-15']/ul/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2741de67-bfea-47c8-8068-22a4cbab9880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-social-link-label</value>
      <webElementGuid>1ef0d815-47ac-4753-8b63-7784b6bb4f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instagram</value>
      <webElementGuid>af7ab372-9c9e-4e50-9e7e-a97ca1ef31a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-15&quot;)/ul[@class=&quot;wp-block-social-links has-visible-labels is-layout-flex wp-block-social-links-is-layout-flex&quot;]/li[@class=&quot;wp-social-link wp-social-link-instagram  wp-block-social-link&quot;]/a[@class=&quot;wp-block-social-link-anchor&quot;]/span[@class=&quot;wp-block-social-link-label&quot;]</value>
      <webElementGuid>688f040d-7c87-4358-8a43-b9b5a215fd44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-15']/ul/li[2]/a/span</value>
      <webElementGuid>0b6a75f6-ee43-431c-9b13-f821c2b730a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a/span</value>
      <webElementGuid>f20b4559-ec35-46fc-a16b-5818580cc64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Instagram' or . = 'Instagram')]</value>
      <webElementGuid>8ce4173c-ed37-438b-b45c-d01a67433bfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
